### ISSUE TITLE
"fail" error when calling flash loan

### ISSUE THREAD

**Issue by nervodatascience** [jerskisnow/Polygon-Arbitrage-Bot#7]
the transactions are working but when you call the execute function from the error contact

see below

[https://polygonscan.com/tx/0x1255d2847f1b90cf3743b415f128cb31614e7966199057bd197b36ff58534b21]()

**Comment by OnlyF0uR** [comment]
This is possibly caused by a discrepancy between de calculated profit and the actual profit that was made. This is essential in order to pay back the flashloan (Because of the premium fee). The entire transaction will be reverted if you fail to pay this fee, you could try fiddling around with that a bit. Also the current flashloan contract and some other components are not exactly up to date anymore.

If there is anyone who would like to work on this particular issue then please submit a PR.

**Comment by OnlyF0uR** [comment]
Laid the groundwork for a V2 that resolves this issue
